### ISSUE TITLE
feature request: ability to disable specific checkers

### ISSUE THREAD

**Issue by scop** [Antonboom/testifylint#12]
Would be nice to be able to disable specific checkers.

Use cases:
- Enable all, but disable some specific checker, `--enable-all --disable=some-specific-checker`
- Use with golangci-lint and use its defaults for this linter otherwise, but disable some specific one instead of having to repeat the whole config
    - Workaround:
        ```yaml
        issues:
          exclude:
            - "^some-specific-checker: "
        ```
